export default {
  MOVIES: 'MOVIES',
  PAGINATED_MOVIES: 'PAGINATED_MOVIES',
  CURRENT_PAGE: 'CURRENT_PAGE',
  LAST_SEARCH: 'LAST_SEARCH',
  FAV_MOVIE_IDS: 'FAV_MOVIE_IDS',
  FAV_MOVIES: 'FAV_MOVIES',
  FAV_MOVIE_IDS_DELETE: 'FAV_MOVIE_IDS_DELETE',
  FAV_MOVIES_DELETE_BY_ID: 'FAV_MOVIES_DELETE_BY_ID',
  FETCHED_SHOWS: 'FETCHED_SHOWS',
  TOTAL_FOUND: 'TOTAL_FOUND',
  CURRENT_QUERY: 'CURRENT_QUERY',
};
